apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Username: "admin"
  Jwt__Issuer: "OrchestrationAPI"
  Jwt__Audience: "https://api.OrchestrationAPI.com"
  Serilog__MinimumLevel__Default: "Debug"
  Elasticsearch__Uri: "http://elasticsearch-service:9200"