apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          # Substituído automaticamente pela pipeline (kubectl set image) a cada deploy.
          image: fcgacr.azurecr.io/fcg-catalog-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-configmap
            - secretRef:
                name: catalog-api-secret